### ISSUE TITLE
Hi,How to use？

### ISSUE THREAD

**Issue by boyfoo** [mikerourke/go-twain#1]
Hi, I'm a rookie，How do I run this program step by step？

**Comment by mikerourke** [comment]
Hi @boyfoo, I started this project as a cross-platform way to interact with scanners, but I hit a huge roadblock when I tried to get the Data Source stuff working correctly. I couldn't get the dynamic loading and `cgo` wrapper to behave with shared libraries, so I gave up and ended up building what I needed in Swift and using the macOS `ImageCaptureCore` APIs.

I should probably make this repo private considering it's not very useful. If I ever end up getting it working though, I'll be sure to let you know. Sorry about that!

**Comment by mario-imperato** [comment]
Mike, excuse me. I'm not completely sure if I understand your answer. Is this repo still alive? And can be used to do scanning in Go on Windows platform or not (you mention a roadblock but mention mac-os).
Thank you
Mario

**Comment by mikerourke** [comment]
Hey @mario-imperato, the short answer is: no, the repo is not still alive, and I'm no longer working on the project. I never tested it on Windows or added any code to get it working on Windows 😢. I'm going to archive it now and add a note to the README. Sorry about that!
